contato/urls.py
from django.urls import path
from . import views 

app_name = 'contato'

urlpatterns = [
    path('contato/', views.contato, name="contato"),
]

login/urls.py
from django.urls import path
from . import views 

app_name = 'login'

urlpatterns = [
    path('login', views.logar, name="login"),
   
]

prjpeconfortavelltda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),

    
    path('produtos/', include("produtos.urls", namespace='produtos') ),
    path('cliente/', include("cliente.urls", namespace='clientes') ),
    path('contato/', include("contato.urls", namespace='contato') ),
    path('fornecedor/', include("fornecedor.urls", namespace='fornecedor') ),
    path('venda/', include("venda.urls", namespace='venda') ),
    path('login/', include("login.urls", namespace='login') ),
]

produtos/urls.py
from django.urls import path
from . import views 

app_name = 'produtos'

urlpatterns = [
    path('lista/', views.listar, name="listar"),
    path ('cadastro/', views.cadastrar, name="cadastrar"),
]

produtos/models.py
from django.db import models

# Create your models here.
class Produto(models.Model):
    codigo = models.AutoField(primary_key=True, help_text='Código único do produto')
    nome = models.CharField(max_length=70, help_text='Informe o nome do produto')
    preco_compra = models.FloatField(help_text='Informe o preço de compra do produto')
    preco_venda = models.FloatField(help_text='Informe o preço de venda do produto')
    cor = models.CharField(max_length=20, help_text='Informe a cor do produto')
    dt_fabricacao = models.DateField(help_text='Informe a data de fabricação do produto')
    imagem = models.CharField(max_length=25, help_text='Informe o nome da imagem do produto')
    
    def __str__(self):
        return f'{self.nome}'

produtos/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.Form):
    codigo = forms.IntegerField(help_text='Código único do produto')
    nome = forms.CharField(max_length=70, help_text='Informe o nome do produto')
    preco_compra = forms.FloatField(help_text='Informe o preço de compra do produto')
    preco_venda = forms.FloatField(help_text='Informe o preço de venda do produto')
    cor = forms.CharField(max_length=20, help_text='Informe a cor do produto')
    dt_fabricacao = forms.DateField(help_text='Informe a data de fabricação do produto')
    imagem = forms.CharField(max_length=25, help_text='Informe o nome da imagem do produto')
    

produtos/views.py
from django.shortcuts import render, redirect
from .models import Produto
from .forms import ProdutoForm

# Create your views here.
def cadastrar(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            dados_produto = form.cleaned_data
            produto_obj = Produto(
                nome = dados_produto ['nome'],
                preco_compra = dados_produto ['preco_compra'],
                preco_venda = dados_produto ['preco_venda'],
                cor =  dados_produto ['cor'],
                dtfabricacao= dados_produto ['dtfabricacao'],
                imagem = dados_produto ['imagem'],
            )
            produto_obj.save()

        return redirect(request, 'produtos/listaprd.html')
    else:
        form = ProdutoForm()
    return render(request, 'produtos/cadastroprd.html', {'form': form})

def listar(request):
    produtos = Produto.objects.all()
    contexto = {
        'produtos': produtos
    }
    return render(request, 'produtos/listaprd.html', context=contexto)

produtos/templates/produtos/cadastroprd.html
{% extends "base.html" %}


{% block title %}
    <title>Produtos</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'produtos:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'produtos:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 mx-auto my-font-family">

       <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Produto</h2>
            </div>
        </div>



        <form action="{% url 'produtos:cadastrar' %}" method="POST" name="frmCadastrarProduto" id="idFrmCadastrarProduto">
            {% csrf_token %}
            <div class="form-group">
                <label for='idNome'>Nome</label>
                <input class="form-control" type='text' id='idNome' name='nome' placeholder='Informe o nome do Produto' required>
            </div>
            <div class="form-group">
                <label for='idPrecoCompra'>Preço de compra</label>
                <input class="form-control" type='text' id='idPrecoCompra' name='preco_compra' placeholder='Informe o preço de compra do Produto' required>
            </div>
            <div class="form-group">
                <label for='idPrecoVenda'>Preço de Venda</label>
                <input class="form-control" type='text' id='idPrecoVenda' name='preco_venda' placeholder='Informe o preço de venda do Produto' required>
            </div>
            <div class="form-group">
                <label for='idCor'>Cor</label>
                <input class="form-control" type='text' id='idCor' name='cor' placeholder='Informe a cor do Produto' required>
            </div>
            <div class="form-group">
                <label for='idDataFabricacao'>Data de Fabricação</label>
                <input class="form-control" type='date' id='idDataFabricacao' name='data_fabricacao' required>
            </div>
            <div class="form-group">
                <label for='idImagem'>Imagem</label>
                <input class="form-control" type='file' id='idImagem' name='imagem' required>
            </div>
            <div class='form-group text-center'>
                <input type='reset'  value='Limpar' class='btn btn-secondary btn-md'>
                <input type='submit' value='Cadastrar' class='btn btn-secondary btn-md' id="btnCadastrarProduto">
            </div>
        </form>
    </main>



{% endblock %}

produtos/templates/produtos/listaprd.html
{% extends "base.html" %}


{% block title %}
    <title>Produtos</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'produtos:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'produtos:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}


{% block corpo %}

<main class="container m-2 mx-auto my-font-family">

       <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Listar Produtos</h2>
            </div>
        </div>

        {% if produtos %}

        <div class="table-responsive">

           
            <table class="table
                        table-borderless
                        text-center
                        my-table-hover
                        my-table-image
                        my-table-td-first-child
                        my-table-border-bottom
                        my-table-th
                        w-100">

               
                <thead>
                   
                    <tr>
                      
                        <th>Nome</th>
                        <th>Preço de Compra</th>
                        <th>Preço de Venda</th>
                        <th>Cor</th>
                        <th>Data de Fabricação</th>
                        <th>Imagem</th>
                    </tr>
                </thead>

            {% for produto in produtos %}
                <tr>
                    <td> {{produto.nome}} </td>
                    <td> {{produto.preco_compra}} </td>    
                    <td> {{produto.preco_venda}} </td> 
                    <td> {{produto.cor}} </td>
                    <td> {{produto.data_fabricacao}} </td>
                    <td> {{produto.imagem}} </td>
                    
                    <td>
                        <a href= '#' class = "btn btn-mini" href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></a><i class="far fa-edit"></i></a>
                        <button type="button" class="btn" role="button" data-target="#modalExcluircliente"
                                data-toggle="modal"  data-descricao="{{cliente.nome}}" data-url="{% url 'cliente:excluir_cliente'  %}">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </td>
                </tr>
            
            {% endfor %}
            </table>

        </div>

        {% else %}
            <div class="text-center">
                <p>Produtos não cadastrados!</p>
            </div>
        {% endif %}

    </main>

    <div class="modal fade" id="modalExcluirTitulo" role="dialog" aria-labelledby="Confirmação" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered">
        
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <p id="mensagemExclusao"></p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnExcluir">Excluir</button>
            </div>

        </div>

    </div>
</div>
{% endblock %}

{% block javascript_complementar %}

    <script type="text/javascript">
        $(document).ready(function() {
            $('#modalExcluirTitulo').on('show.bs.modal', function(event) {
                var descricao = $(event.relatedTarget).data('descricao');
                var urlExcluir = $(event.relatedTarget).data('url');
                $("#mensagemExclusao").html('Deseja excluir  <b>' + descricao + '</b> ?');

                $.fn.excluirTitulo = function() {
                    var url = $(event.relatedTarget).data('url');
                    location.replace(url);
                }
            });
        
            $("#btnExcluir").on('click', function() {
                $.fn.excluirTitulo();
                return false;
            });            
        });
    </script>


{% endblock %}