contato/urls.py
from django.urls import path
from . import views 

app_name = 'contato'

urlpatterns = [
    path('contato/', views.contato, name="contato"),
]

fornecedor/urls.py
from django.urls import path
from . import views 

app_name = 'fornecedor'

urlpatterns = [
    path('lista/', views.listar, name="listar"),
    path ('cadastro/', views.cadastrar, name="cadastrar"),
]

login/urls.py
from django.urls import path
from . import views 

app_name = 'login'

urlpatterns = [
    path('login', views.logar, name="login"),
   
]

prjpeconfortavelltda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),

    
    path('produtos/', include("produtos.urls", namespace='produtos') ),
    path('cliente/', include("cliente.urls", namespace='clientes') ),
    path('contato/', include("contato.urls", namespace='contato') ),
    path('fornecedor/', include("fornecedor.urls", namespace='fornecedor') ),
    path('venda/', include("venda.urls", namespace='venda') ),
    path('login/', include("login.urls", namespace='login') ),
]

fornecedor/models.py
from django.db import models

# Create your models here.
class Fornecedor(models.Model):
    codigo = models.AutoField(primary_key=True, help_text='Informe o Código do fabricante')
    nome = models.CharField(max_length=70, help_text='Informe o nome do fabricante')

    def __str__(self):
        return f'{self.nome}'

fornecedor/forms.py
from django import forms
from .models import Fornecedor

class FornecedorForm(forms.Form):
    codigo = forms.IntegerField(help_text='Informe o Código do fabricante', required=True)
    nome = forms.CharField(max_length=70, help_text='Informe o nome do fabricante', required=True)

fornecedor/views.py
from django.shortcuts import render, redirect
from .forms import FornecedorForm
from .models import Fornecedor

# Create your views here.
def listar(request):
    lista_fornecedor = Fornecedor.objects.all()
    contexto = {
        'fornecedor': lista_fornecedor
    }
    return render(request, 'fornecedores/listafrn.html')


def cadastrar(request):
    if request.method == 'POST':
        form = FornecedorForm(request.POST)
        if form.is_valid():
            dados_fornecedor = form.cleaned_data
            cliente_obj = Fornecedor(
                codigo = dados_fornecedor['codigo'],
                nome = dados_fornecedor ['nome'],
            )
            cliente_obj.save()
        return redirect ('fornecedor:listar')
    else:
        form = FornecedorForm()
    return render(request, 'fornecedores/cadastrofrn.html')

fornecedor/templates/fornecedores/cadastrofrn.html
{% extends "base.html" %}


{% block title %}
    <title>Portal do Fornecedor</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'fornecedor:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'fornecedor:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 mx-auto my-font-family">
        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Fornecedor</h2>
            </div>
        </div>

        <form action="{% url 'fornecedor:cadastrar' %}" method="POST" name="frmCadastrarFornecedor" id="idFrmCadastrarFornecedor">
            {% csrf_token %}
            <div class="form-group">
                <label for='idNome'>Nome</label>
                <input class="form-control" type='text' id='idNome' name='nome' placeholder='Informe o nome do fornecedor' required>
            </div>
            
            <div class='form-group text-center'>
                <input type='reset'  value='Limpar' class='btn btn-secondary btn-md'>
                <input type='submit' value='Cadastrar' class='btn btn-secondary btn-md' id="btnCadastrarFornecedor">
            </div>
        </form>
    </main>
{% endblock %}

fornecedor/templates/fornecedores/listafrn.html
{% extends "base.html" %}


{% block title %}
    <title>Portal do Fornecedor</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'fornecedor:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'fornecedor:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}


{% block corpo %}

<main class="container m-2 mx-auto my-font-family">

       <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Listar Fornecedores</h2>
            </div>
        </div>

        {% if fornecedor %}

        <!-- tabela responsiva -->
        <div class="table-responsive">

            <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
            <table class="table
                        table-borderless
                        text-center
                        my-table-hover
                        my-table-image
                        my-table-td-first-child
                        my-table-border-bottom
                        my-table-th
                        w-100">
            
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Nome</th>
                        
                    </tr>
                </thead>''
                <tbody>
                    {% for fornecedor in fornecedores %}
                        <tr>
                            <td>{{ fornecedor.codigo }}</td>
                            <td>{{ fornecedor.nome }}</td>
                            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <p class="text-center">Nenhum fornecedor cadastrado.</p>
        {% endif %}
</main>
{% endblock %}