cliente/urls.py
from django.urls import path
from . import views 

app_name = 'clientes'

urlpatterns = [
    path('lista/', views.listar, name="listar"),
    path('cadastro/', views.cadastro, name="cadastro"),
    path('cadastrar/', views.cadastrar, name="cadastrar"),
    # path('excluir/', views.excluir, name="excluir_cliente"),
    path('carregar_cliente/', views.carregar_cliente, name="carregar_cliente"),
    path('atualizar_cliente/', views.atualizar_cliente, name="atualizar_cliente"),
    ]

contato/urls.py
from django.urls import path
from . import views 

app_name = 'contato'

urlpatterns = [
    path('contato/', views.contato, name="contato"),
]

login/urls.py
from django.urls import path
from . import views 

app_name = 'login'

urlpatterns = [
    path('login', views.logar, name="login"),
   
]

prjpeconfortavelltda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),

    
    path('produtos/', include("produtos.urls", namespace='produtos') ),
    path('cliente/', include("cliente.urls", namespace='clientes') ),
    path('contato/', include("contato.urls", namespace='contato') ),
    path('fornecedor/', include("fornecedor.urls", namespace='fornecedor') ),
    path('venda/', include("venda.urls", namespace='venda') ),
    path('login/', include("login.urls", namespace='login') ),
]

cliente/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    cpf = models.CharField(max_length=11, help_text='Informe seu CPF com apenas números, sem pontos ou traços')
    nome = models.CharField(max_length=70, help_text='Nome completo')
    endereco = models.CharField(max_length=100, help_text='Endereço completo')   
    telefone = models.CharField(max_length=11, help_text='Informe seu telefone com apenas números, sem espaços ou traços')
    estado_domicilio = models.CharField(max_length=2, help_text='Informe a sigla do seu estado, por exemplo: SP, RJ, MG')
    cidade = models.CharField(max_length=50, help_text='Informe o nome da sua cidade')
    genero = models.CharField(max_length=1, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')])
    contato = models.CharField(max_length=1, choices=[('C', 'Para carta'), ('E', 'Para e-mail'), ('T', 'Para telefone'), ('F', 'Para fax')])
    email = models.CharField(max_length=100, help_text='Informe seu e-mail')
    usuario = models.CharField(max_length=100, help_text='Confirme o e-mail informado')
    senha = models.CharField(max_length=256, help_text='Informe uma senha segura')
    
    def __str__(self):
        return f'Olá, {self.nome}'

cliente/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.Form):
    nome = forms.CharField(max_length=70, required=True, help_text='Informe o nome completo do cliente')
    cpf = forms.CharField(max_length=11, required=True, help_text='Informe o CPF do cliente')
    endereco = forms.CharField(max_length=100, required=True, help_text='Informe o endereço do cliente')
    cidade = forms.CharField(max_length=50, help_text='Informe o nome da sua cidade',required=True)
    telefone = forms.CharField(max_length=11, required=True, help_text='Informe o telefone do cliente')
    estado_domicilio = forms.CharField(max_length=2, required=True, help_text='Informe o estado de domicílio do cliente')
    contato = forms.CharField(max_length=1, required=True)
    email = forms.CharField(max_length=100, required=True)
    genero = forms.CharField(max_length=1, required=True)
    contato = forms.CharField(max_length=1, required=True)
    email = forms.CharField(max_length=100, help_text='Informe seu e-mail', required=False)
    
    

class ClienteAtualizarForm(forms.ModelForm):
    nome = forms.CharField(max_length=70, required=True, help_text='Informe o nome completo do cliente')
    cpf = forms.CharField(max_length=11, required=True, help_text='Informe o CPF do cliente')
    endereco = forms.CharField(max_length=100, required=True, help_text='Informe o endereço do cliente')
    telefone = forms.CharField(max_length=11, required=True, help_text='Informe o telefone do cliente')
    estado_domicilio = forms.CharField(max_length=2, required=True, help_text='Informe o estado de domicílio do cliente')
    email = forms.CharField(max_length=100, required=True)
    genero = forms.CharField(max_length=1, required=True)
    contato = forms.CharField(max_length=1, required=True)
    email = forms.CharField(max_length=100, help_text='Informe seu e-mail', required=False)

cliente/views.py
from django.shortcuts import render, redirect
from .models import Cliente
from .forms import ClienteForm, ClienteAtualizarForm

# Create your views here.

def cadastrar(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            dados_cliente = form.cleaned_data
            cliente_obj = Cliente(
                nome = dados_cliente['nome'],
                cpf = dados_cliente['cpf'],
                endereco = dados_cliente ['endereco'],
                telefone = dados_cliente['telefone'],
                estado_domicilio = dados_cliente['estado_domicilio'],
                cidade = dados_cliente['cidade'],
                genero = dados_cliente['genero'],
                contato = dados_cliente['contato'],
                email = dados_cliente ['email'],
            )
            cliente_obj.save()
        return redirect('clientes:listar')
    else:
        form = ClienteForm()
    return render(request, 'clientes/cadastroclt.html', {'form': form})

def listar(request):
    clientes = Cliente.objects.all()
    contexto = {
        'clientes': clientes
    }
    return render(request, 'clientes/listaclt.html', context=contexto)


def cadastro(request):
    return render(request, 'clientes/cadastroclt.html')





def exclui(request, cpf):
    excluir_cliente = Cliente.objects.get(cpf=cpf)
  
    excluir_cliente.delete()

    return redirect('clientes:listar')


def carregar_cliente(request, cpf):
    cliente = Cliente.objects.get(cpf=cpf)
    contexto = {
        'clientes': cliente,
    }

    return render (request, 'clientes/atualizarCliente.html', context=contexto)
    
    

def atualizar_cliente (request):
    if request.method == 'POST':
        form = ClienteAtualizarForm(request.POST)
        if form.is_valid():
            dados_cliente = form.cleaned_data
            cpf = dados_cliente['cpf']
            cliente = Cliente.objects.get(cpf=cpf)
            cliente.nome = dados_cliente['nome']
            cliente.endereco = dados_cliente['endereco']
            cliente.telefone = dados_cliente['telefone']
            cliente.email = dados_cliente['email']
            Cliente.save()
            
        else: 
            print (form.errors)
    return redirect('cliente:listar')

cliente/templates/clientes/cadastroclt.html
<!-- {% extends "base.html" %} -->
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/cadastroclt.css' %}">
{% endblock %}




{% block title %}
    <title>Portal do Cliente </title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'clientes:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'clientes:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 mx-auto my-font-family">

       <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 ">Cadastro de Cliente</h2>
            </div>
        </div>



        <form action="{% url 'clientes:cadastrar' %}" method="POST" name="frmCadastrarCliente" id="idFrmCadastrarCliente">
            {% csrf_token %}
            <div class="form-group">
                <label for='idNome'>Nome</label>
                <input class="form-control" type='text' id='idNome' name='nome' placeholder='Informe o nome do cliente' required>
            </div>
            <div class="form-group">
                <label for='idCPF'>CPF</label>
                <input class="form-control" type='text' id='idCPF' name='cpf' placeholder='Informe o CPF do cliente' required>
            </div>
            <div class="form-group">
                <label for='idEndereco'>Endereço</label>
                <input class="form-control" type='text' id='idEndereco' name='endereco' placeholder='Informe o endereço do cliente' required>
            </div>



            <div class="form-group">
                <p>Escolha seu estado de domicílio:</p>

                <label  for='idEstadoDomicilio'> 
                    <select class="form-control" id='idEstadoDomicilio' name='estado_domicilio' required>
                    <option value="/">Selecione...</option> 
                    <option value="RJ">Rio de Janeiro (RJ)</option>   
                    <option value="SP">São paulo (SP)</option>  
                    <option value="MG">Minas Gerais (MG)</option>  
                    <option value="ES">Espirito Santo (ES)</option>  
                    <option value="PR">Paraná (PR)</option> 
                    <option value="BA">Bahia (BA)</option> 
                    <option value="RS">Rio Grande do Sul (RS)</option> 
                    </select>

                </label>
            </div>
            <br>

            <div class="form-row">
                <label for='idCidade'>Cidade</label>
                <input class="form-control" type='text' id='idCidade' name='cidade' placeholder='Informe a cidade do cliente' required>
            </div>

            <br>

            <div class ="form-row">
                <p>Gênero</p>
                <label for='idGenero'>
                    <select class="form-control" id='idGenero' name='genero' required>   
                    <option value="/">Selecione...</option> 
                    <option value="M"> Masculino</option> 
                    <option value="F"> Feminino </option>
                    <option value="O"> Outro </option>
                    </select> 
                </label>

            </div>
            <br>
            <div class="form-row">
                <p>Formas de contato</p>
                <label for='idContato'>
                    <select class="form-control" id="idFormasContato" name="contato" required >
                    <option value="/">Selecione...</option>     
                    <option value="T" > Telefone </option>
                    <option value="E" > Email </option>
                    <option value="F" > Fax </option>
                    <option value="C" > Carta </option>
                    </select>
                </label>
            </div>
            <div class="form-group">
                <label for='idEmail'>Email</label>
                <input class="form-control" type='email' id='idEmail' name='email' placeholder='Informe o email do cliente' required>
            </div>
            <div class="form-group">
                <label for='idTelefone'>Telefone</label>
                <input class="form-control" type='number' id='idTelefone' name='telefone' placeholder='Informe o telefone do cliente' required>
            </div>
            <div class='form-group text-center'>
                <input type='reset'  value='Limpar' class='btn btn-secondary btn-md'>
                <input type='submit' value='Cadastrar' class='btn btn-secondary btn-md' id="btnCadastrarCliente">
            </div>
        </form>
    </main>



{% endblock %}

cliente/templates/clientes/listaclt.html
{% extends "base.html" %}


{% block title %}
    <title>Portal do Cliente</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'clientes:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'clientes:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}


{% block corpo %}

<main class="container m-2 mx-auto my-font-family">

       <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Listar Clientes</h2>
            </div>
        </div>

        {% if cliente %}

        <div class="table-responsive">

           
            <table class="table
                        table-borderless
                        text-center
                        my-table-hover
                        my-table-image
                        my-table-td-first-child
                        my-table-border-bottom
                        my-table-th
                        w-100">

               
                <thead>
                   
                    <tr>
                      
                        <th>CPF</th>
                        <th>Nome</th>
                        <th>Endereço</th>
                        <th>Telefone</th>
                        <th>Estado de Domicilio</th>
                        <th>Cidade</th>
                        <th>Gênero</th>
                        <th>Contato</th>
                        <th>Email</th>
                    </tr>
                </thead>

            {% for cliente in clientes %}
                <tr>
                    <td> {{cliente.cpf}} </td>
                    <td> {{cliente.nome}} </td>    
                    <td> {{cliente.endereco}} </td> 
                    <td> {{cliente.telefone}} </td>
                    <td> {{cliente.estado_domicilio}} </td>
                    <td> {{cliente.cidade}} </td>
                    <td> {{cliente.genero}} </td>
                    <td> {{cliente.contato}} </td>
                    <td> {{cliente.email}} </td>
                    <td> {{cliente.cidade}}</td>
                    <td>
                        <a href= '{% url "cliente:carregar_cliente" %}' class = "btn btn-mini" href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></a><i class="far fa-edit"></i></a>
                        <button type="button" class="btn" role="button" data-target="#modalExcluircliente"
                                data-toggle="modal"  data-descricao="{{cliente.nome}}" data-url="{% url 'cliente:excluir_cliente'  %}">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </td>
                </tr>
            
            {% endfor %}
            </table>

        </div>

        {% else %}
            <div class="text-center">
                <p>Clientes não cadastrados!</p>
            </div>
        {% endif %}

    </main>

    <div class="modal fade" id="modalExcluirTitulo" role="dialog" aria-labelledby="Confirmação" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered">
        
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <p id="mensagemExclusao"></p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnExcluir">Excluir</button>
            </div>

        </div>

    </div>
</div>
{% endblock %}

{% block javascript_complementar %}

    <script type="text/javascript">
        $(document).ready(function() {
            $('#modalExcluirTitulo').on('show.bs.modal', function(event) {
                var descricao = $(event.relatedTarget).data('descricao');
                var urlExcluir = $(event.relatedTarget).data('url');
                $("#mensagemExclusao").html('Deseja excluir  <b>' + descricao + '</b> ?');

                $.fn.excluirTitulo = function() {
                    var url = $(event.relatedTarget).data('url');
                    location.replace(url);
                }
            });
        
            $("#btnExcluir").on('click', function() {
                $.fn.excluirTitulo();
                return false;
            });            
        });
    </script>


{% endblock %}