contato/urls.py
from django.urls import path
from . import views 

app_name = 'contato'

urlpatterns = [
    path('contato/', views.contato, name="contato"),
]

login/urls.py
from django.urls import path
from . import views 

app_name = 'login'

urlpatterns = [
    path('login', views.logar, name="login"),
   
]

prjpeconfortavelltda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),

    
    path('produtos/', include("produtos.urls", namespace='produtos') ),
    path('cliente/', include("cliente.urls", namespace='clientes') ),
    path('contato/', include("contato.urls", namespace='contato') ),
    path('fornecedor/', include("fornecedor.urls", namespace='fornecedor') ),
    path('venda/', include("venda.urls", namespace='venda') ),
    path('login/', include("login.urls", namespace='login') ),
]

venda/urls.py
from django.urls import path
from . import views 

app_name = 'venda'

urlpatterns = [
    path('lista', views.listar, name="listar"),
    path ('registro', views.registrar, name="registrar"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    {% block title %}
    {% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- define e insere um favicon no documento HTML -->
    <link href="{% static 'static/img/logo.jpg' %}" rel="shortcut icon">

    <!-- versao gratuita do Font Awesome icons-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <!-- insira este conteudo aqui que representa o CSS do Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Google  icons -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
</head>

<body>

    <!-- seu codigo comeca aqui -->

    <!-- container bootstrap -->
    <header class="container px-0">

        <nav class="navbar navbar-expand-lg navbar-light bg-white px-0">

            <!-- logo -->
            <div>
                <a class="my-color-purple mx-left">
                    <img src="{% static 'static/img/logo.jpg' %}" class="w-25 float-start">
                </a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynavbar"
                aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Navegação Alternativa">
                Menu <span class="navbar-toggler-icon"></span>
            </button>

            <!-- menu -->
             {% block menu %}
             {% endblock %} 
            
        </nav>

        {% block titulo_pagina %}
        {% endblock %}
        
    </header>

    {% block corpo %}
    {% endblock %}

    <footer class="container text-center">
        <div class="row border-primary bg-white">
            <div class="col font copyright ">
                <p>&copy; Pé Confortável Ltda</p>
            </div>
        </div>
    </footer>

    <!-- seu codigo termina aqui -->

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>

    {% block javascript_complementar %}
    {% endblock %}

</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
    <title>Pé Confortável</title>
{% endblock %}



{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
                <div class="navbar-nav">
                    <a href="/" class="nav-link">Início</a>
                    <a href="{% url 'cliente:listar' %}" class="nav-link">Cliente</a>
                    <a href="{% url 'fabricante:listar' %}" class="nav-link">Fabricante</a>
                    <a href="{% url 'produto:listar' %}" class="nav-link">Produtos</a>
                    <a href="{% url 'venda:listar' %}" class="nav-link">Vendas</a>
                    <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
                </div>
    </div>
{% endblock %}  

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    <title>Pé Confortável</title>
{% endblock %}


{% block titulo_pagina %}
    <h1 class="text-center my-h1 my-font-family">Pé Confortável</h1>
{% endblock %}



{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
                <div class="navbar-nav">
                    <a href="/" class="nav-link">Início</a>
                    <a href="{% url 'clientes:listar' %}" class="nav-link">Cliente</a>
                    <a href="{% url 'fornecedor:listar' %}" class="nav-link">Fabricante</a>
                    <a href="{% url 'produtos:listar' %}" class="nav-link">Produtos</a>
                    <a href="{% url 'venda:listar' %}" class="nav-link">Vendas</a>
                    <a href="{% url 'contato:contato' %}" class="nav-link">Contato</a>
                </div>
    </div>
{% endblock %}  

{% block corpo %}
    <main class="container m-2 mx-auto color-text my-font-family my-body">
        <div class="row mb-50">
            <div class="col text-center m-0">
                <p class="my-p">Onde o seu conforto começa pelos pés</p>
            </div>
        </div>
            
        <br>
        <br>
        <br>

        <div class="row m-80">
            <div class="col-md-6">
                <h2>Sobre Nós</h2>
                <p class="my-p">Na Pé Confortável, acreditamos que cada passo importa. Desde 2025, oferecemos calçados que combinam estilo, qualidade e conforto para toda a família.</p>
            </div>
            <div class="col-md-6">
                
                <img src="{% static 'static/img/img1.jpg' %}" class="mx-auto d-block w-50" alt="Fachada da loja">
            </div>
        </div>
            
        <br>
        <br>
        <br>
        
        <div class="row m-80 p-10">
            <div class="col-md-6 order-md-2">
                <h2>Nossos Produtos</h2>
                <p class="my-p">Trabalhamos com uma ampla variedade de marcas de calçados: Adidão, Naike, Pulma, Olímpicos, Pontão, Meião, Reboco, Paquetás, Mizduno, Tiadora. Nossos produtos são selecionados com rigor para garantir conforto e durabilidade.</p>
            </div>
            <div class="col-md-6 order-md-1">
                
                <img src="{% static 'static/img/img2.jpg' %}" class="mx-auto d-block w-25" alt="Produtos em destaque">
            </div>
        </div>

        <br>
        <br>
        <br>
       
        <div class="row mb-5">
            <div class="col-md-6">
                <h2>Atendimento Personalizado</h2>
                <p class="my-p">Nosso atendimento é feito por profissionais preparados para te ajudar a encontrar o calçado ideal para sua necessidade, com simpatia e respeito.</p>
            </div>
            <div class="col-md-6 order-md-1">
                
                <img src="{% static 'static/img/img3.jpg' %}" class="mx-auto d-block w-50" alt="Produtos em destaque">
            </div>
        </div>
       
        <br>
        <br>
        <br>
       
    </main>
{% endblock %}